FROM python:3.12


WORKDIR /app


COPY app/req.txt /app/req.txt


RUN pip install --no-cache-dir -r /app/req.txt


COPY ./app /app/app

WORKDIR /app

ENV PYTHONPATH=/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
