version: "3.8"

services:
  fastapi2:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: fastapi2
    env_file:
      - .env
    depends_on:
      - db2
    networks:
      - app-network
    expose:
      - "8000"

  db2:
    image: postgres:17
    container_name: postgres2
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis2:
    image: redis:7
    container_name: redis2
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx2:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx2
    ports:
      - "80:80"
    depends_on:
      - fastapi2
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
