"""initial

Revision ID: 49953e8c4c10
Revises: 
Create Date: 2025-05-19 16:59:36.152083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49953e8c4c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_request_by_contest_and_method',
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('last_request', sa.DateTime(timezone=True), server_default=sa.text("(now() - interval '365 days')"), nullable=False),
    sa.PrimaryKeyConstraint('contest_id', 'method')
    )
    op.create_index(op.f('ix_last_request_by_contest_and_method_contest_id'), 'last_request_by_contest_and_method', ['contest_id'], unique=False)
    op.create_index(op.f('ix_last_request_by_contest_and_method_method'), 'last_request_by_contest_and_method', ['method'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_request', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_requests')
    op.drop_table('users')
    op.drop_index(op.f('ix_last_request_by_contest_and_method_method'), table_name='last_request_by_contest_and_method')
    op.drop_index(op.f('ix_last_request_by_contest_and_method_contest_id'), table_name='last_request_by_contest_and_method')
    op.drop_table('last_request_by_contest_and_method')
    # ### end Alembic commands ###
